name: Nasa Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses : actions/checkout@v2
      - name : Use Nodejs v16
        uses : actions/setup-node@v2
        with :
          node-version : '16'
      - run : npm install --force
      - run : npm install react-scripts --force
      - run : npm install react-dom react --force
      - run : npm run build --prefix clients